version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/kotlin-keywords-app"
    schedule:
      interval: "yearly"

  - package-ecosystem: "gradle"
    directory: "/test-app"
    schedule:
      interval: "yearly"

  - package-ecosystem: "gradle"
    directory: "/test-app-2r"
    schedule:
      interval: "yearly"
